/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRCMessageModule"
 * 	found in "RRCMessage.asn1"
 */

#ifndef	_ID_H_
#define	_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ID {
	ID_rrcSetupRequest	= 0,
	ID_rrcSetup	= 1,
	ID_rrcSetupComplete	= 2
} e_ID;

/* ID */
typedef long	 ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ID;
asn_struct_free_f ID_free;
asn_struct_print_f ID_print;
asn_constr_check_f ID_constraint;
ber_type_decoder_f ID_decode_ber;
der_type_encoder_f ID_encode_der;
xer_type_decoder_f ID_decode_xer;
xer_type_encoder_f ID_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ID_H_ */
#include <asn_internal.h>
